# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Snake GitHub Contribution

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Snake Action
      uses: Platane/snk@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
